#!/bin/sh
# Simple theme-switcher script.
# author https://github.com/rxyhn

# var
########
awesome=$HOME/.config/awesome/rc.lua
configuration=$HOME/.config/awesome/configuration
term=$HOME/.config/alacritty/alacritty.yml

# Beautiful day themes
#########################
day () {
  # colorscheme
  sed -i "17s/.*/theme = themes[1]/g" $awesome
  # picom
  sed -i "12s/.*/shadow-opacity = 0.55;/g" $configuration/picom.conf
  # alacritty
  sed -i "66s/.*/  *light/g" $term
  # rofi
  sed -i "12s/.*/@import \"..\/themes\/day\/day.rasi\"/g" $configuration/rofi.rasi
}

# Aesthetic night themes
###########################
night () {
  # colorscheme
  sed -i "17s/.*/theme = themes[2]/g" $awesome
  # picom
  sed -i "12s/.*/shadow-opacity = 0.75;/g" $configuration/picom.conf
  # alacritty
  sed -i "66s/.*/  *dark/g" $term
  # rofi
  sed -i "12s/.*/@import \"..\/themes\/night\/night.rasi\"/g" $configuration/rofi.rasi
}

case $1 in
    day)
    day
    ;;

    night)
    night
    ;;

    *)
esac
