require("ui.notifications.battery")
require("ui.notifications.brightness")
require("ui.notifications.layoutlist")
require("ui.notifications.notifs")
require("ui.notifications.playerctl")
require("ui.notifications.volume")
