require("module.auto-start")
require("module.bling")
require("module.rubato")
require("module.layout-machi")
require("module.better-resize")
require("module.exit-screen")
require("module.savefloats")
require("module.window_switcher").enable()
